;;; julia-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from julia-ts-misc.el

(register-definition-prefixes "julia-ts-misc" '("julia-ts--"))


;;; Generated autoloads from julia-ts-mode.el

(add-to-list 'auto-mode-alist '("\\.jl\\'" . julia-ts-mode))
(autoload 'julia-ts-mode "julia-ts-mode"
"Major mode for Julia files using tree-sitter.

In addition to any hooks its parent mode `julia-mode' might have run,
this mode runs the hook `julia-ts-mode-hook', as the final or
penultimate step during initialization.

\\{julia-ts-mode-map}" t)
(register-definition-prefixes "julia-ts-mode" '("julia-ts-"))

;;; End of scraped data

(provide 'julia-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; julia-ts-mode-autoloads.el ends here
