;;; eglot-jl-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eglot-jl.el

(autoload 'eglot-jl-init "eglot-jl"
"Load `eglot-jl' to use eglot with the Julia language server." t)
(register-definition-prefixes "eglot-jl" '("eglot-jl-"))

;;; End of scraped data

(provide 'eglot-jl-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eglot-jl-autoloads.el ends here
