;;; weather-scout-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from weather-scout.el

(register-definition-prefixes "weather-scout" '("weather-scout-"))


;;; Generated autoloads from weather-scout-icons.el

(register-definition-prefixes "weather-scout-icons" '("weather-scout--"))

;;; End of scraped data

(provide 'weather-scout-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; weather-scout-autoloads.el ends here
